org: jonathonklem1
service: atfgundbmiddleware # Name of our service

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: us-east-1
  memorySize: 128 # 1MB increments, minimum 128, affects pricing
  environment:
    ALLOWED_ORIGIN: ${ssm:/ATFGUNDBMiddleware/config/allowed_origin}
    MONGO_URL: ${ssm:/ATFGUNDBMiddleware/config/mongodb_url}

package:
  exclude:
    - ./**
  include:
    - ./bin/aws
    - ./bin/.env

# Frontend deploy config
custom:
  stage: ${opt:stage, self:provider.stage}
  client:
    bucketName: dashboard.atfgundb.com # Must be globally unique, if you're setting a custom domain, then use that. (ex: example.com)
    distributionFolder: frontend/build # If you named your frontend project something else, change this here.
    existing: true
    errorDocument: index.html


# Endpoint config
functions:
  DoEverything:
    handler: bin/aws
    events:
      - http:
          path: /guns
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /guns/add
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /guns/edit
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /guns/addMaintenance
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /guns/addAccessory
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /ammo
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /ammo/add
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /ammo/edit
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /ammo/dispose
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /ammo/purchase
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /users/saveVisit
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /range/addTrip
          method: post
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /range/getDateAndAmmoReport
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /range/getAmmoReport
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /range/getGunReport
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /guns/remove
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /users/delete
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /ammo/remove
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
      - http:
          path: /range/getRangeTrips
          method: get
          cors: true # This allows OPTION requests to pass trough the AWS API Gateway
# Frontend deploy plugin config
plugins:
  - serverless-finch
# this doesn't appear to be neccesary after the resource was created, leaving here for posterity
#resources:
#  - ${file(resources/s3-bucket.yml)}